/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Luminary ATS Design System
        "surface-container-highest": "#e1e2eb",
        "on-primary-container": "#fefcff",
        "tertiary": "#006b2b",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-tint": "#005ac1",
        "surface-container-high": "#e7e7f1",
        "surface-dim": "#d8d9e3",
        "surface-container": "#ecedf7",
        "surface-variant": "#e1e2eb",
        "on-secondary-container": "#415680",
        "background": "#f9f9ff",
        "on-surface-variant": "#424753",
        "inverse-surface": "#2e3038",
        "secondary-container": "#b7ccfd",
        "surface-container-lowest": "#ffffff",
        "primary": "#0058bd",
        "on-primary": "#ffffff",
        "primary-container": "#2771df",
        "outline-variant": "#c2c6d5",
        "secondary": "#495e89",
        "on-tertiary": "#ffffff",
        "outline": "#727785",
        "tertiary-container": "#008738",
        "secondary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004494",
        "on-tertiary-container": "#f7fff2",
        "surface-container-low": "#f2f3fd",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff0fa",
        "surface": "#f9f9ff",
        "on-surface": "#191b22",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 8px 24px rgba(25,27,34,0.06)",
        "ambient-lg": "0 12px 32px rgba(25,27,34,0.08)",
      },
    },
  },
  plugins: [],
}
